package yaber

import (
	"strings"
	"testing"
)

var data = map[string]interface{}{
	"version": "testver",
	"package": "testpkg",
	"command": "testcmd",
	"tag":     "testtag",
	"files": map[string][]byte{
		"TESTFILE": []byte("TESTFILEBODY"),
	},
}

const expectedHeader string = `//go:generate testcmd

// Code generated by yaber vtestver (https://github.com/lmas/yaber)
// DO NOT EDIT.

package testpkg`

func TestRunTemplateDev(t *testing.T) {
	out, e := runTemplate(tmplDev, data)
	failOnError(t, e)
	s := string(out)
	if !strings.HasPrefix(s, "// +build !testtag\n\n"+expectedHeader) {
		t.Errorf("Got bad header for dev template: %s", s)
	}
}

func TestRunTemplateBuild(t *testing.T) {
	out, e := runTemplate(tmplBuild, data)
	failOnError(t, e)
	s := string(out)
	if !strings.HasPrefix(s, "// +build testtag\n\n"+expectedHeader) {
		t.Errorf("Got bad header for build template: %s", s)
	}
	if !strings.Contains(s, "TESTFILE") && !strings.Contains(s, "TESTFILEBODY") {
		t.Errorf("No files in build template: %s", s)
	}
}
