package yaber

import (
	"strings"
	"testing"
)

var data = map[string]interface{}{
	"version": "testver",
	"package": "testpkg",
	"command": "testcmd",
	"tag":     "testtag",
	"files": map[string][]byte{
		"TESTFILE": []byte("TESTFILEBODY"),
	},
}

const expectedHeader string = `//go:generate testcmd

// Code generated by yaber vtestver (https://github.com/lmas/yaber)
// DO NOT EDIT.

package testpkg`

func TestRunMainTemplate(t *testing.T) {
	out, e := runTemplate(tmplMain, data)
	failOnError(t, e)
	s := string(out)
	if !strings.HasPrefix(s, expectedHeader) {
		t.Errorf("Got bad header for main template: %s", s)
	}

	if !strings.Contains(s, "TESTFILE") && !strings.Contains(s, "TESTFILEBODY") {
		t.Errorf("No files in main template: %s", s)
	}
}
